services:
  python_dev:
    image: takuver4/ty_env_v2:rev06
    restart: unless-stopped

    environment:
      PYTHONPATH: "/work/src/ty_lib"

      # for GUI
      DISPLAY: ${DISPLAY}

    volumes:
      - /mnt/c/Users/toruv/OneDrive/work/sample_code:/work/src

      # for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix

    stdin_open: true
    tty: true
