from __future__ import annotations

from pathlib import Path
import re
from typing import Any
import os
import sys
import numpy as np
from itertools import product

THIS_FILE = Path(__file__).resolve()
THIS_DIR = THIS_FILE.parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from create_hdr_media import (
    MDCV_PRIMARIES_LIST,
    MDCV_LUMINANCE_LIST,
    CLLI_LUMINANCE_LIST,
    KIND_AV1,
    KIND_AVIF,
    KIND_HEVC,
    KIND_PNG,
    make_media_file_name_without_ext
)



_CHUNK_HEADER_RE = re.compile(r"\bchunk\s+([A-Za-z0-9]{4})\b")
_PRIMARY_RE = re.compile(
    r"(White|Red|Green|Blue)\s*x\s*=\s*([0-9]*\.?[0-9]+)\s*y\s*=\s*([0-9]*\.?[0-9]+)"
)
_RANGE_RE = re.compile(r"\b(Full|Narrow)\s+range\b", re.IGNORECASE)
_MAX_LUM_RE = re.compile(r"Maximum luminance\s*=\s*([0-9]*\.?[0-9]+)\s*cd/m\^2")
_MIN_LUM_RE = re.compile(r"Minimum luminance\s*=\s*([0-9]*\.?[0-9]+)\s*cd/m\^2")
_MAX_CLL_RE = re.compile(
    r"Maximum content light level\s*=\s*([0-9]*\.?[0-9]+)\s*cd/m\^2"
)
_MAX_FALL_RE = re.compile(
    r"Maximum frame average light level\s*=\s*([0-9]*\.?[0-9]+)\s*cd/m\^2"
)

_PRIMARY_ORDER = ["White", "Red", "Green", "Blue"]


def _split_chunks(lines: list[str]) -> dict[str, str]:
    chunk_positions: list[tuple[str, int]] = []
    for idx, line in enumerate(lines):
        match = _CHUNK_HEADER_RE.search(line)
        if match:
            chunk_positions.append((match.group(1), idx))

    chunk_texts: dict[str, str] = {}
    for pos, (chunk_name, start_idx) in enumerate(chunk_positions):
        end_idx = chunk_positions[pos + 1][1] if pos + 1 < len(chunk_positions) else len(lines)
        chunk_texts[chunk_name] = "\n".join(lines[start_idx:end_idx])

    return chunk_texts


def _parse_primaries(chunk_text: str) -> np.ndarray | None:
    found: dict[str, tuple[float, float]] = {}
    for name, x_str, y_str in _PRIMARY_RE.findall(chunk_text):
        found[name] = (float(x_str), float(y_str))

    if not all(name in found for name in _PRIMARY_ORDER):
        return None

    return np.array([found[name] for name in _PRIMARY_ORDER], dtype=np.float64)


def parse_png_chunk_dump(dump_txt_file: str | Path) -> dict[str, Any]:
    """Parse pngcheck dump text and extract cICP/mDCV/cLLI metadata.

    Args:
        dump_txt_file: Path to a text file generated by `pngcheck -v`.

    Returns:
        Dictionary with three keys: `cicp`, `mdcv`, `clli`.
        Each value is either a dictionary with parsed fields or `None`
        when the corresponding chunk is not present.
    """
    text = Path(dump_txt_file).read_text(encoding="utf-8")
    chunk_texts = _split_chunks(text.splitlines())

    cicp_data: dict[str, Any] | None = None
    if "cICP" in chunk_texts:
        cicp_text = chunk_texts["cICP"]
        primaries = _parse_primaries(cicp_text)
        range_match = _RANGE_RE.search(cicp_text)
        cicp_data = {
            "chromaticity": primaries,
            "range": None if range_match is None else range_match.group(1).capitalize() + " range",
        }

    mdcv_data: dict[str, Any] | None = None
    if "mDCV" in chunk_texts:
        mdcv_text = chunk_texts["mDCV"]
        primaries = _parse_primaries(mdcv_text)
        max_match = _MAX_LUM_RE.search(mdcv_text)
        min_match = _MIN_LUM_RE.search(mdcv_text)
        luminance = None
        if max_match and min_match:
            luminance = np.array(
                [float(max_match.group(1)), float(min_match.group(1))], dtype=np.float64
            )
        mdcv_data = {
            "chromaticity": primaries,
            "luminance_cd_m2": luminance,
        }

    clli_data: dict[str, Any] | None = None
    if "cLLI" in chunk_texts:
        clli_text = chunk_texts["cLLI"]
        max_cll_match = _MAX_CLL_RE.search(clli_text)
        max_fall_match = _MAX_FALL_RE.search(clli_text)
        light_levels = None
        if max_cll_match and max_fall_match:
            light_levels = np.array(
                [float(max_cll_match.group(1)), float(max_fall_match.group(1))],
                dtype=np.float64,
            )
        clli_data = {
            "light_level_cd_m2": light_levels,
        }

    return {
        "cicp": cicp_data,
        "mdcv": mdcv_data,
        "clli": clli_data,
    }

if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    mdcv_primaries_list = MDCV_PRIMARIES_LIST
    mdcv_luminance_list = MDCV_LUMINANCE_LIST
    clli_luminance_list = CLLI_LUMINANCE_LIST
    for mdcv_primaries, mdcv_luminance, clli_luminance\
        in product(mdcv_primaries_list, mdcv_luminance_list, clli_luminance_list):

        file_name_without_ext = make_media_file_name_without_ext(
            kind=KIND_PNG,
            suffix=None,
            mdcv_primaries=mdcv_primaries,
            mdcv_luminance=mdcv_luminance,
            clli_luminance=clli_luminance
        )
        file_name = f"./data/{Path(file_name_without_ext).name}.png.txt"
        print(file_name)
        if os.path.exists(file_name):
            result = parse_png_chunk_dump(dump_txt_file=file_name)
            print(result)
        else:
            continue
