version: '3.9'

services:
    python_dev:
        image: takuver4/ultrahdr:rev02
        environment: 
            PYTHONPATH: "/work/src/ty_lib"
            DISPLAY: host.docker.internal:0.0
        volumes:
            - /Users/toru/Work/sample_code:/work/src
        stdin_open: true
