ARG DEBIAN_VERSION="bookworm"
ARG PYTHON_VERSION="3.12"

FROM python:${PYTHON_VERSION}-${DEBIAN_VERSION} as builder

# Avoid clearing `DEBIAN_VERSION`
ARG DEBIAN_VERSION
ARG PYTHON_VERSION

WORKDIR /root/local

RUN echo "deb http://ftp.jp.debian.org/debian/ ${DEBIAN_VERSION} main" > /etc/apt/sources.list \
    && echo "deb http://security.debian.org/ ${DEBIAN_VERSION}-security main" >> /etc/apt/sources.list \
    && apt-get update && apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        build-essential \
        cmake \
        git-core \
        libaom-dev \
        libass-dev \
        libdav1d-dev \
        libde265-dev \
        libfreetype6-dev \
        libgnutls28-dev \
        libheif-dev \
        libmp3lame-dev \
        libsdl2-dev \
        libtool \
        libunistring-dev \
        libva-dev \
        libvdpau-dev \
        libvorbis-dev \
        libvpx-dev \
        libx264-dev \
        libx265-dev \
        libxcb1-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        meson \
        ninja-build \
        pkg-config \
        texinfo \
        wget \
        yasm \
        zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install FFmpeg
RUN git clone https://github.com/FFmpeg/FFmpeg.git -b n7.0.2
#     && cd FFmpeg \
#     && ./configure \
#     && make -j16 \
#     && make install \
#     && cd /root/local \
#     && rm -rf /root/local/FFmpeg

RUN ldconfig

CMD ["bash"]
